FT2-40: Added a new single text field to the above form that will accept email id.
swarnavd/MOD-2_Training_Group_PHP pull request #5
Opened 2024-03-04 16:38 UTC by swarnavd

User will enter email id and on submit, check if correct email id syntax has been used.
Show a message on successful email syntax or show an error message on the wrong syntax.

2024-03-17 14:08 UTC, innoDebrup commented on result.php
> +$namePattern = '/^[a-zA-Z]+$/';
```suggestion
$namePattern = '/^[a-zA-Z]+$/';
```

2024-03-17 14:23 UTC, innoDebrup requested changes
- Please use PHP Alternate Control Syntax wherever applicable instead of using multiple PHP blocks in a random manner in HTML parts. It makes debugging problematic.
- Please increase code modularity by migrating few portions to separate files.

2024-03-17 14:23 UTC, innoDebrup commented on result.php
> +$namePattern = '/^[a-zA-Z]+$/';
`$namePattern = '/^[a-zA-Z]+$/';`
Explain more about this regular expression. What is it checking?

2024-03-17 14:23 UTC, innoDebrup commented on result.php
> +  $trimmed = preg_replace($namePattern, " ", $fullName);
`$trimmed = preg_replace($namePattern, " ", $fullName);`
Explain what we are doing with this statement.

2024-03-18 06:00 UTC, swarnavd commented
> * Please use PHP Alternate Control Syntax wherever applicable instead of using multiple PHP blocks in a random manner in HTML parts. It makes debugging problematic.

2024-03-18 06:00 UTC, closed without merging